spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  flyway:
    enabled: true

aws:
  region: ${AWS_REGION:ap-northeast-1}

management:
  tracing:
    sampling:
      probability: 0.5

logging:
  level:
    com.eventpick: DEBUG
